# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.TextField()),
                ('price', models.IntegerField()),
                ('rate', models.FloatField()),
                ('date', models.DateField()),
                ('image', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
    ]
